blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/jaywongX/zen-search/discussions
    about: Please ask usage questions here. 
templates:
- title: Bug Report
  filename: bug_report.md
- title: Feature Request
  filename: feature_request.md